const puppeteer = require("puppeteer");
const fs = require("fs");
const OUT = "C:/Users/nioh1/Desktop/PMO-Portal-Deliverables/home-v2";
(async () => {
  if (!fs.existsSync(OUT)) fs.mkdirSync(OUT, { recursive: true });
  const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox"] });
  const page = await browser.newPage();
  await page.setViewport({ width: 1500, height: 1100, deviceScaleFactor: 1 });
  await page.evaluateOnNewDocument(() => localStorage.setItem("pmo_mock_email", "admin@pmo.test"));
  const errors = [];
  page.on("pageerror", e => errors.push(String(e).slice(0, 250)));
  await page.goto("http://localhost:5199/", { waitUntil: "networkidle2", timeout: 40000 });
  await new Promise(r => setTimeout(r, 2600));
  await page.screenshot({ path: `${OUT}/01-home-top.png` });
  const scrollMain = (y) => page.evaluate((yy) => {
    const m = document.querySelector("main") || document.scrollingElement;
    m.scrollTop = yy;
  }, y);
  await scrollMain(760);
  await new Promise(r => setTimeout(r, 500));
  await page.screenshot({ path: `${OUT}/02-home-mid.png` });
  await scrollMain(1520);
  await new Promise(r => setTimeout(r, 500));
  await page.screenshot({ path: `${OUT}/03-home-perf.png` });
  await scrollMain(99999);
  await new Promise(r => setTimeout(r, 500));
  await page.screenshot({ path: `${OUT}/04-home-depts.png` });
  console.log(errors.length ? "ERRORS: " + errors.join(" ;; ") : "no page errors");
  await browser.close();
})();
